### ISSUE TITLE
Zoomed in search should notify you of results outside

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#161]
results to your search not in your window don't show up.

Let's have a popup box that says "hey you've got x results matching your search, click to expand"

**Comment by almasaeed2010** [comment]
I don't remember what this issue is referring to. What will be in the popup box once a user click on the expand button?

**Comment by bradfordcondon** [comment]
Dana would have the map zoomed in on an area and search, and was confused to get no results. 

So the feature was if user searches an gets no results, *but* would get results if they werent zoomed in to limit results, theres a notice that tells them hey if you we zoom you out, you'll find stuff.
