### ISSUE TITLE
 API documentation

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#192]
We need to document our API as we move towards making our data available to partners.

We need to think about providing BOTH anonymous (Cartogratree) and full info trees (ACF dentatabase).

**Comment by almasaeed2010** [comment]
We'll need to create a consumer API that's not intended to serve the site or the mobile app for others to explore. We can easily implement Laravel Passport for this and allow users to authenticate to the API directly making it possible for users with more privileges to view accurate locations. 

The new API end-points should not be comprehensive, all we need is 2 methods. 
- [ ] List all observations with ability to specify a count and a page along with simple filters like observation name and starting period (date).
- [ ] Show observation to allow pulling of observation details

**Comment by almasaeed2010** [comment]
See #311
