### ISSUE TITLE
csv data download convert JSON

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#203]
>One question I have is regarding the CSV format. Is there any way that the additional data column could be split out into discrete fields? Being in one field would make it more difficult to convert into DentataBase-friendly format.

My response: 

>Yes that would be doable.  Right now the data is in JSON.   The only consideration is that each tree species has different data fields… but I bet we can set those values to `na` for species without those questions.  I’ll get back to you when we’ve gotten a chance to work on it.

**Comment by almasaeed2010** [comment]
Done in live.
