### ISSUE TITLE
keywords for google

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#218]
hiking
naturalist

@mestato

**Comment by almasaeed2010** [comment]
This is still an issue since google doesn't show treesnap unless the user has typed the word "treesnap" or "tree snap".

<img width="913" alt="Screen Shot 2019-04-17 at 9 07 59 AM" src="https://user-images.githubusercontent.com/1512664/56290052-51a9a280-60f0-11e9-8e00-ffdee443cab2.png">
