### ISSUE TITLE
clear out duplicate entries

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#277]
We previously had duplicates uploaded due to Android image submission size i believe.

We need to clean out the duplicate entries now while its still managable.

**Comment by bradfordcondon** [comment]
Response to G. Doyle (see: two Trees Snap accounts on one phone?) when cleaned.  33 vs 190 records

**Comment by almasaeed2010** [comment]
To clean up, use the following command:
`php artisan observations:flush-duplicates` 

This command will detect and remove duplicate observations while keeping the most recent copy.

This run (June 1, 2018) returned: `Deleted 285 duplicate observation(s)`

**Comment by almasaeed2010** [comment]
Also G. Doyle now has 33 observations (did he not submit anything since he sent that email?)

**Comment by almasaeed2010** [comment]
Done!
