### ISSUE TITLE
collection creation streamlining UX

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#282]
observations page: change text to indicate you can create collection by pressing star.

![screen shot 2018-05-31 at 2 53 04 pm](https://user-images.githubusercontent.com/7063154/40801996-606c62ae-64e2-11e8-959d-4bbf8150d40a.png)

collections page:
 If no collection, it says 
>You have not created any collections yet. You can create new collections in the Map page.

Instead it should indicate maps OR Observations page.

**Comment by almasaeed2010** [comment]
<img width="392" alt="screen shot 2018-06-05 at 10 44 44 pm" src="https://user-images.githubusercontent.com/1512664/40999073-758f013a-6912-11e8-97cb-ab35a574af46.png">
<img width="1175" alt="screen shot 2018-06-05 at 10 40 23 pm" src="https://user-images.githubusercontent.com/1512664/40999076-78d26332-6912-11e8-9f99-99d05775a3ee.png">

Done and live
