### ISSUE TITLE
Bulk selection and download of observations

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#283]
From Taylor. The problem: I want to download a csv with a large set of trees (say, all the trees I sampled). It is tedious to create a very large collection by clicking stars, and instead I'd like to do it with an easy search/filter query instead. 

Possible solutions:

1. Allow download of all items currently matching a filter
2. Use filter style functionality to add items to a new or existing collection 

I tend to like 1 as it is simpler. But i can see users wanting to create collections with a bulk query. Yet the filters vs collections divide gets so fuzzy at that point.

**Comment by bradfordcondon** [comment]
I like both features.

**Comment by almasaeed2010** [comment]
I like 1 as well. We can add an additional field to limit the submission date range. That way you can specify anything submitted in 2018 or the month of May for example.

**Comment by almasaeed2010** [comment]
Ok I've reworked the downloader class such that we can add observation downloads practically everywhere (Groups, Collections, Filters, My Observations, Admin Observations etc). Currently we have support for both collections and filters. If it is desirable, we can add elsewhere too. Please create an issue for any page you'd like to see a download button.

Done and live for filters.
