### ISSUE TITLE
need title truncation on film roll map for long species names

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#289]
![screen shot 2018-06-05 at 11 15 09 am](https://user-images.githubusercontent.com/7063154/40985281-c96d4b2e-68b1-11e8-9596-829789f6974c.png)

**Comment by almasaeed2010** [comment]
Fixed and live

<img width="256" alt="screen shot 2018-06-05 at 10 29 08 pm" src="https://user-images.githubusercontent.com/1512664/40998258-e6450cce-690f-11e8-9134-a11e70d74433.png">
