### ISSUE TITLE
Support measurement units in filters

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-website#310]
Add support to measurement units in website filters.

**Comment by almasaeed2010** [comment]
- [ ] Add a migration that attaches the correct units for the current observations
- [ ] When saving an observation in the DB, convert all units to metric. This allows us to take input from the user during filtering and search for a single unit (less DB operations), then convert back when displaying to the user in their preferred unit.

**Comment by bradfordcondon** [comment]
FYI o made US units default on app.  It’s what American users would expect.  We could set by region...?

**Comment by almasaeed2010** [comment]
Yeah that's what I was thinking too. I've used a package before to determine the locale of the device and if it is anything other than en_US we can set to metric.

**Comment by almasaeed2010** [comment]
PR #319 adds the last part of this issue by allowing advanced filtering using units. It does not matter what the original observation unit is, this implementation will automatically convert and apply the correct unit! It also adds the ability to switch between metrics while viewing an observation (see below) along with allowing the user to adjust their units setting from the site directly.

<img width="981" alt="screen shot 2018-07-06 at 2 19 31 pm" src="https://user-images.githubusercontent.com/1512664/42394297-a7ae9cca-8127-11e8-9e70-0892cb9117a6.png">
