### ISSUE TITLE
Browser map pop up about fuzzy location persists

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#331]
Even after clicking "remember this" the pop up continues to return every time the page is loaded (Leigh of Torreya)

**Comment by almasaeed2010** [comment]
This doesn't happen to me on Chrome. Maybe we should ask her which browser is she using to help identify the issue.

**Comment by almasaeed2010** [comment]
Tested on Chrome, FireFox, Safari, MSIE11, and MSEdge. Works on all platforms.

I think she mistook the `x` button with the `don't show this again`. Only the white `don't show this again` button remembers the setting. It's also set to reshow the warning after 1 month in case it is a public computer.

**Comment by almasaeed2010** [comment]
not replicable on our end. I'll close.
