### ISSUE TITLE
navigation complaint: going to full description means you cant go back 

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#337]
You lose your place on the map if you go to an individual observation, and she requests a popup.  Maybe she isnt aware that all the info is in the sidebar?

**is** all the info in the sidebar?  Or is there some stuff you have to visit the observation page to see?

**Comment by almasaeed2010** [comment]
Clicking on markers/thumbnails moves the map closer to the selected observation. Maybe we don't want it to do this?

**Comment by almasaeed2010** [comment]
- [ ] Save zoom and position state into url so that when users hit the back button they get back to the same position

**Comment by almasaeed2010** [comment]
Fixed in #346 

The map now will remember your last location when you hit the back button from an observation page that you visited from the map.
