### ISSUE TITLE
Map speedup suggestion

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-website#342]
Currently, we load all the data for visible observations on the map. This means we can have thousands of observations loaded at once when what the user actually sees is just simple info like the title and position. Let's cut back on what we send to the user and lazy load the rest of the info when the user clicks on a marker.

- [x] Location
- [x] Thumbnail
- [x] Title + otherLabel
- [ ] Collection date
- [ ] User name

**Comment by almasaeed2010** [comment]
I read a bit about server side clustering and I think that will give us exactly what we need in terms of performance. Let's consider implementing that for TreeSnap.

**Comment by jwest60** [comment]
As a temporary solution, we could try just upping the default zoom level to 8.

**Comment by almasaeed2010** [comment]
Zoom set to 8. Speed noticeably faster.

**Comment by noah-77** [comment]
Sufficiently resolved in #573
