### ISSUE TITLE
Add tanoak to the trees page

### ISSUE THREAD

**Issue by jwest60** [statonlab/Treesnap-website#406]
https://treesnap.org/trees

i assume this needs to be done

**Comment by jwest60** [comment]
added [here](https://github.com/statonlab/Treesnap-website/tree/tanoak-trees)

![image](https://user-images.githubusercontent.com/32902460/47865949-ee42e700-ddd3-11e8-8d89-cb04b5879052.png)

**Comment by almasaeed2010** [comment]
Merged. Thanks @jwest60
