### ISSUE TITLE
Torreya logo update and info update

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#446]
New logo for their partnership with FNPS:
![FNPS](https://user-images.githubusercontent.com/508122/56210814-9a942500-6024-11e9-9ee5-533b0edf0901.jpg)

Proposed text (have sent via email to get feedback):
The Mission of the Florida Native Plant Society is to promote the preservation, conservation, and restoration of the native plants and native plant communities of Florida. The FNPS is officially partnered with TorreyaKeepers, a group dedicated to saving the Florida torreya (<i>Torreya taxifolia</i>). One of the most endanged conifers in the world, the Florida torreya is  has a limited native range in Florida and Georgia and only a few hundred remaining individuals. Data collected from TreeSnap will be used to find remaining trees and track their health.

**Comment by mestato** [comment]
Updated text from Leigh:
"The Mission of the Florida Native Plant Society is to promote the preservation, conservation, and restoration of the native plants and native plant communities of Florida. The FNPS TorreyaKeepers Project is dedicated to saving the Florida Torreya (Torreya taxifolia) in its native habitat. One of the most endangered conifers in the world, the Florida Torreya has a limited native range in Florida and Georgia and only a few hundred remaining individuals in the wild. Data collected from TreeSnap will be used to find remaining trees and track their health."

**Comment by almasaeed2010** [comment]
done.
