### ISSUE TITLE
limit routes by RouteServiceProvider

### ISSUE THREAD

**Issue by jwest60** [statonlab/Treesnap-website#450]
bad URLs return a status of 200 instead of 404

**Comment by almasaeed2010** [comment]
Any idea which route is doing this?

**Comment by almasaeed2010** [comment]
@jwest60 do you remember which page caused this error?

**Comment by jwest60** [comment]
any URL that isnt in routes will trigger it

https://treesnap.org/badurl

this displays a 404 visually, but programmatically the response will return 200
