### ISSUE TITLE
Add share observation UI 

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-website#454]
Now that we have a share API, we want to add some sort of UI for it. 

Currently, we have a share button in the ObservationCard and ObservationDetails components. I think we should extend those to provide a form for sharing.

**Comment by jwest60** [comment]
added a modal that looks like this

![image](https://user-images.githubusercontent.com/32902460/57800080-7e1c0300-771e-11e9-8f01-803f428f3f4a.png)

not super pretty but it should be easy to customize later

**Comment by jwest60** [comment]
![image](https://user-images.githubusercontent.com/32902460/57948187-f6b1c980-78ae-11e9-99e1-9833278419e3.png)

![image](https://user-images.githubusercontent.com/32902460/57948211-07fad600-78af-11e9-95db-a7682bc316c3.png)

updated modal

**Comment by jwest60** [comment]
available for testing on [this branch](https://github.com/statonlab/Treesnap-website/tree/sharelink-ui)

at the moment the modal only appears on the observation details form, but it should appear on the observation card as well, i just couldnt figure out how it should look

**Comment by almasaeed2010** [comment]
Can we move the message to under the link's text box?

**Comment by almasaeed2010** [comment]
Also limit the width of the textbox itself to 300px
