### ISSUE TITLE
Add Oregon Ash filters

### ISSUE THREAD

**Issue by jwest60** [statonlab/Treesnap-website#477]
https://github.com/statonlab/Treesnap-mobile/issues/614

After the above issue gets resolved, we should add the corresponding filters for the species to the website

**Comment by jwest60** [comment]
![image](https://user-images.githubusercontent.com/32902460/65342566-02850380-dba1-11e9-9311-5f63b901179a.png)

I've added the filters for what we have at the moment, will keep updated as we decide on the final wording for questions and choices

**Comment by almasaeed2010** [comment]
live. thanks!
