### ISSUE TITLE
Add DGRC as a partner

### ISSUE THREAD

**Issue by jwest60** [statonlab/Treesnap-website#478]
> USDA Forest Service Dorena Genetic Resource Center (DGRC):  DGRC is a regional facility that specializes in working with genetic resistance to diseases and insects, as well as gene conservation and genetic variation studies. As a TreeSnap partner, they (and cooperators) will use data on ash to find trees that are resistant to the emerald ash borer, to learn basic information on the genetic variation in the species and to initiate ex situ gene conservation using some of the seed.

I think we can just use the logo from the other USDA site in the Scientific Partners section

**Comment by almasaeed2010** [comment]
We might want to use the Forest Service logo but let's ask first. For the time being, I'll push what we have and ask what they want to do.
