### ISSUE TITLE
Make note that -2 accuracy means manually entered coordinates for admins

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#495]
For an observation with a -2 location accuracy, this means the coordinates were entered manually. We should display that information along side the coordinates. something like this...

![Screen Shot 2020-03-06 at 10 40 58 AM](https://user-images.githubusercontent.com/508122/76098288-2d201880-5f97-11ea-8817-b5aa2174be4e.png)

https://treesnap.org/observation/5605

**Comment by almasaeed2010** [comment]
What do you think about changing the "Within -2 meters radius" in location Accuracy to "Manually entered by user"?

**Comment by mestato** [comment]
Yes, thats even better

**Comment by almasaeed2010** [comment]
done
