### ISSUE TITLE
Allow users to create a science sampling project

### ISSUE THREAD

**Issue by jwest60** [statonlab/Treesnap-website#521]
Allow users to create a Science Sampling project with a form.

The goal: Create a form that upon submission, creates a new Sampling Project model in the database using the API. You will need to make a POST request to `/web/sampling-projects` to accomplish this.

For the form:
- Select public or private GPS coordinates
- Create a name for the project
- Define traits; this will be a free text box
- Add project participants; this will allow the user to select other users on the site; maybe a tokens field?

If you have any questions, feel free to ask!

**Comment by mestato** [comment]
This is a whole new project now, no need to pursue within treesnap.
