### ISSUE TITLE
Label photos related to specific questions

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#535]
Would be nice to label photos taken regarding specific questions (not just general image capture).

For example, for ash, it asks for photos of the tree. Then if you check "yes" to flowers being present, it specifically asks for a photo of the flowers. It would be nice to label that.

**Comment by almasaeed2010** [comment]
done

**Comment by almasaeed2010** [comment]
<img width="383" alt="Screen Shot 2021-04-21 at 5 18 06 PM" src="https://user-images.githubusercontent.com/1512664/115622230-919a5600-a2c5-11eb-9a2d-10fe0f2c9275.png">
