### ISSUE TITLE
search for unique id does not work on map

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#536]
Search for unique id works in observation panes but not on map. This would make it difficult to find a tree by id without being a scientist or admin.

A tree observation I made: 4562239075

My Observations
https://treesnap.org/account/observations/?page=1
works in "Search"

Admin Observations
https://treesnap.org/admin/observations?page=1&view=6&collection=-1
works in "Search"

Map
https://treesnap.org/map/?center=35.16189803125315,-84.33819542368265&zoom=6
Does not work in "Filters"

**Comment by almasaeed2010** [comment]
done
