### ISSUE TITLE
"Recent Updates" feed on main page

### ISSUE THREAD

**Issue by noah-77** [statonlab/Treesnap-website#624]
We're pretty frequently updating treesnap and treesnap's protocols, but at first glance the site apparently doesn't seem active. A "Recent Updates" box could function as a good marketing tool for Treesnap, and perhaps for our other apps as well? I envision updates like the following:

"The Hemlock survey has been updated to support the Lingering Hemlock Protocol (link to the working group or somesuch)"
"A bug regarding X has been fixed"
"TreeSnap Plots has been published!"

I can make the portfolio show this same feed.

**Comment by chance-stribling** [comment]
Recent updates are now displayed on the landing page next to recent observations. New observations can now be created and edited by logged in users. Component may eventually need infinite scrolling as the number of updates increases.
