### ISSUE TITLE
Observation Page has layout issues

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#637]
https://treesnap.org/observation/4947

Pictures are overlapping with buttons at various screen sizes.

<img width="1176" alt="Screenshot 2024-07-31 at 10 33 50 AM" src="https://github.com/user-attachments/assets/403f3fbd-38b7-4316-9b60-f5b762adff43">

**Comment by chance-stribling** [comment]
Made changes to the css, buttons now wrap instead of being hidden by the image.
